### ISSUE TITLE
Vagrant up failure

### ISSUE THREAD

**Issue by rmadaka** [gluster/gcs#21] opened 2018-10-10 10:08 UTC
If we don't comment the below line in Vagrantfile, Vagrant up will fail.

Under gcs/deploy/Vagrantfile, if i don't comment this particular line "config.vagrant.plugins = ["vagrant-libvirt"]"  vagrant up will fail.

File name : Vagrantfile
File path: gcs/deploy

After commenting this particular line "config.vagrant.plugins = ["vagrant-libvirt"]" vagrant up is success.

**Comment by Madhu-1** [comment] 2018-10-10 10:09
duplicate of #20

**Comment by amarts** [comment] 2018-10-10 10:18
Should we document this somehow, or ask at the end of the log itself to do the commenting ?

**Comment by Madhu-1** [comment] 2018-10-10 11:18
@amarts  as updating vagrant to the latest version will fix this issue
we can do two things,
* Add pre-request  to install  latest vagrant version
* if removing `"config.vagrant.plugins = ["vagrant-libvirt"]"` works on all vagrant version we can do that one to.

@kshlm @JohnStrunk let me know your thoughts on this

**Comment by JohnStrunk** [comment] 2018-10-10 14:42
I think my preferred fix would be to remove the line (assuming no ill consequences w/ newer versions). I encounter the error as well with:
```
$ vagrant --version
Vagrant 2.0.2

$ rpm -qa | grep vagrant
vagrant-libvirt-0.0.40-4.fc28.noarch
vagrant-2.0.2-2.fc28.noarch
vagrant-sshfs-1.3.1-1.fc28.noarch
```

Perhaps someone (@kshlm ?) w/ the latest version can comment on what the line does and whether it is required for newer versions.

**Comment by Madhu-1** [comment] 2018-10-11 12:34
i will sent a patch to fix this issue

**Closed** 2018-10-11 14:55 UTC
Labels: bug
